# Generated by Django 5.2.15 on 2026-08-22 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0006_alter_gruppoorganizzativo_django_group'),
        ('spid_cie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(editable=False, max_length=32, unique=True)),
                ('data_ora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('dettagli', models.CharField(blank=True, max_length=200)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('codice_fiscale', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{16}$', 'Indicare un codice fiscale di 16 caratteri.')])),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('stato', models.CharField(choices=[('PR', 'Prenotata'), ('CO', 'Confermata'), ('AN', 'Annullata'), ('ES', 'Eseguita'), ('NS', 'Assente')], default='PR', max_length=2)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('identita_digitale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni', to='spid_cie.identitadigitale')),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni_pubbliche', to='access_control.ufficio')),
            ],
            options={
                'verbose_name': 'Prenotazione pubblica',
                'verbose_name_plural': 'Prenotazioni pubbliche',
                'ordering': ['-data_ora'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stato__in', ['PR', 'CO'])), fields=('ufficio', 'data_ora'), name='prenotazione_pubblica_slot_unico')],
            },
        ),
    ]
