# Generated by Codex on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0006_alter_gruppoorganizzativo_django_group"),
        ("prenotazioni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatoSincronizzazioneWordPress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chiave", models.CharField(default="appuntamenti", max_length=64, unique=True)),
                ("cursore", models.DateTimeField(blank=True, null=True)),
                ("ultima_esecuzione_il", models.DateTimeField(blank=True, null=True)),
            ],
            options={"verbose_name": "Stato sincronizzazione WordPress", "verbose_name_plural": "Stati sincronizzazione WordPress"},
        ),
        migrations.CreateModel(
            name="MappaturaUfficioWordPress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unita_organizzativa_id", models.CharField(max_length=64)),
                ("luogo_id", models.CharField(max_length=64)),
                ("unita_organizzativa", models.CharField(blank=True, max_length=255)),
                ("aggiornato_il", models.DateTimeField(auto_now=True)),
                ("ufficio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mappature_wordpress", to="access_control.ufficio")),
            ],
            options={"verbose_name": "Mappatura ufficio WordPress", "verbose_name_plural": "Mappature uffici WordPress", "ordering": ["unita_organizzativa", "luogo_id"]},
        ),
        migrations.CreateModel(
            name="AppuntamentoWordPress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origine_id", models.BigIntegerField(db_index=True, unique=True)),
                ("origine_stato", models.CharField(blank=True, max_length=32)),
                ("origine_aggiornato_il", models.DateTimeField(db_index=True)),
                ("prenotato_il", models.DateTimeField(blank=True, null=True)),
                ("data_ora_inizio", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("data_ora_fine", models.DateTimeField(blank=True, null=True)),
                ("unita_organizzativa_id", models.CharField(blank=True, max_length=64)),
                ("unita_organizzativa", models.CharField(blank=True, max_length=255)),
                ("luogo_id", models.CharField(blank=True, max_length=64)),
                ("servizio", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("codice_fiscale", models.CharField(blank=True, max_length=16)),
                ("dettaglio_richiesta", models.TextField(blank=True)),
                ("dati_origine", models.JSONField(blank=True, default=dict)),
                ("acquisito_il", models.DateTimeField(auto_now_add=True)),
                ("sincronizzato_il", models.DateTimeField(auto_now=True)),
                ("ufficio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="appuntamenti_wordpress", to="access_control.ufficio")),
            ],
            options={"verbose_name": "Appuntamento WordPress", "verbose_name_plural": "Appuntamenti WordPress", "ordering": ["-data_ora_inizio", "-origine_id"]},
        ),
        migrations.AddConstraint(
            model_name="mappaturaufficiowordpress",
            constraint=models.UniqueConstraint(fields=("unita_organizzativa_id", "luogo_id"), name="mappatura_ufficio_wordpress_unica"),
        ),
    ]
