# Generated by Codex on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prenotazioni", "0002_wordpress_connector"),
    ]

    operations = [
        migrations.CreateModel(
            name="SedeWordPress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origine_id", models.CharField(max_length=64, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("stato", models.CharField(blank=True, max_length=32)),
                ("aggiornato_il", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Sede WordPress", "verbose_name_plural": "Sedi WordPress", "ordering": ["nome"]},
        ),
        migrations.AddField(
            model_name="mappaturaufficiowordpress",
            name="calendario_wordpress_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="mappaturaufficiowordpress",
            name="sede",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mappature_ufficio", to="prenotazioni.sedewordpress"),
        ),
    ]
