# Generated by Codex on 2026-08-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access_control", "0006_alter_gruppoorganizzativo_django_group"),
        ("prenotazioni", "0003_sedewordpress_mappatura_calendario"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitaOrganizzativaWordPress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origine_id", models.CharField(max_length=64, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("stato", models.CharField(blank=True, max_length=32)),
                ("aggiornato_il", models.DateTimeField(auto_now=True)),
                ("ufficio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="unita_organizzative_wordpress", to="access_control.ufficio")),
            ],
            options={"verbose_name": "Unità organizzativa WordPress", "verbose_name_plural": "Unità organizzative WordPress", "ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="PersonaleWordPress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origine_id", models.CharField(max_length=64, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("nome", models.CharField(blank=True, max_length=150)),
                ("cognome", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("attivo", models.BooleanField(default=True)),
                ("aggiornato_il", models.DateTimeField(auto_now=True)),
                ("utente", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="profili_wordpress", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Persona WordPress", "verbose_name_plural": "Personale WordPress", "ordering": ["cognome", "nome", "username"]},
        ),
        migrations.CreateModel(
            name="AssegnazionePersonaleWordPress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("personale", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="prenotazioni.personalewordpress")),
                ("unita_organizzativa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="prenotazioni.unitaorganizzativawordpress")),
            ],
            options={"verbose_name": "Assegnazione personale WordPress", "verbose_name_plural": "Assegnazioni personale WordPress"},
        ),
        migrations.AddField(
            model_name="personalewordpress",
            name="unita_organizzative",
            field=models.ManyToManyField(blank=True, related_name="personale_wordpress", through="prenotazioni.AssegnazionePersonaleWordPress", to="prenotazioni.unitaorganizzativawordpress"),
        ),
        migrations.AddField(
            model_name="mappaturaufficiowordpress",
            name="unita_organizzativa_wordpress",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mappature_ufficio", to="prenotazioni.unitaorganizzativawordpress"),
        ),
        migrations.AddConstraint(
            model_name="assegnazionepersonalewordpress",
            constraint=models.UniqueConstraint(fields=("personale", "unita_organizzativa"), name="assegnazione_personale_wordpress_unica"),
        ),
    ]
