# Generated by Codex on 2026-08-26

from django.db import migrations, models


def elimina_utenti_tecnici_wordpress(apps, schema_editor):
    """Rimuove l'import iniziale errato degli account tecnici wp_users."""
    PersonaleWordPress = apps.get_model("prenotazioni", "PersonaleWordPress")
    PersonaleWordPress.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("prenotazioni", "0004_unita_personale_wordpress"),
    ]

    operations = [
        migrations.RunPython(elimina_utenti_tecnici_wordpress, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="personalewordpress",
            old_name="username",
            new_name="titolo",
        ),
        migrations.AlterField(
            model_name="personalewordpress",
            name="titolo",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name="personalewordpress",
            name="email",
        ),
        migrations.AddField(
            model_name="personalewordpress",
            name="competenze",
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelOptions(
            name="personalewordpress",
            options={"ordering": ["cognome", "nome", "titolo"], "verbose_name": "Persona pubblica WordPress", "verbose_name_plural": "Persone pubbliche WordPress"},
        ),
    ]
