# Generated by Codex on 2026-08-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prenotazioni", "0005_persone_pubbliche_wordpress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalewordpress",
            name="utente",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="profili_wordpress", to=settings.AUTH_USER_MODEL, verbose_name="Utente Django associato"),
        ),
    ]
