# Generated by Django 5.2.15 on 2026-08-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="PDNDAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("servizio", models.CharField(choices=[("ANPR_SOGGETTO", "ANPR — dati del soggetto"), ("ANPR_FAMIGLIA", "ANPR — composizione famiglia"), ("INPS_ISEE", "INPS — attestazione ISEE"), ("DURC", "DURC — regolarità contributiva")], max_length=20)),
                ("identificativo_hash", models.CharField(db_index=True, max_length=64)),
                ("esito", models.CharField(choices=[("ESEGUITA", "Eseguita"), ("NON_CONFIGURATA", "Servizio non configurato"), ("NEGATA", "Negata dal servizio"), ("ERRORE", "Errore tecnico")], max_length=20)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("dettaglio_errore", models.CharField(blank=True, max_length=500)),
                ("eseguita_il", models.DateTimeField(auto_now_add=True)),
                ("operatore", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="interrogazioni_pdnd", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Audit interrogazione PDND", "verbose_name_plural": "Audit interrogazioni PDND", "ordering": ["-eseguita_il"]},
        )
    ]
