# Generated by Django 5.2.15 on 2026-08-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='presenza_fonte',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Fonte della presenza'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='presenza_verificata_il',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ultima verifica presenza'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stato_presenza',
            field=models.CharField(choices=[('UNK', 'Non verificata'), ('PRE', 'Presente'), ('ASS', 'Assente')], db_index=True, default='UNK', max_length=3, verbose_name='Stato presenza'),
        ),
    ]
