# Generated by Django 5.2.15 on 2026-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_presenza_fonte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_attivita',
            field=models.CharField(choices=[('SPO', 'Sportellista'), ('AMM', 'Amministrativista')], db_index=True, default='AMM', max_length=3, verbose_name='Tipo di attività'),
        ),
    ]
