# Generated by Django 5.2.15 on 2026-08-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_ufficio_numero_visite_media_ufficio_overbooking_and_more'),
        ('accounts', '0003_customuser_tipo_attivita'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotPresenzaUfficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rilevato_il', models.DateTimeField(db_index=True, verbose_name='Rilevato il')),
                ('dipendenti_presenti', models.PositiveSmallIntegerField(default=0, verbose_name='Dipendenti presenti')),
                ('sportellisti_presenti', models.PositiveSmallIntegerField(default=0, verbose_name='Sportellisti presenti')),
                ('dipendenti_totali', models.PositiveSmallIntegerField(default=0, verbose_name='Dipendenti assegnati')),
                ('sportellisti_totali', models.PositiveSmallIntegerField(default=0, verbose_name='Sportellisti assegnati')),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_presenze', to='access_control.ufficio', verbose_name='Ufficio')),
            ],
            options={
                'verbose_name': 'Snapshot presenza ufficio',
                'verbose_name_plural': 'Snapshot presenze uffici',
                'ordering': ['-rilevato_il'],
                'indexes': [models.Index(fields=['ufficio', 'rilevato_il'], name='idx_presenza_ufficio_data')],
            },
        ),
    ]
