# Generated by Django 5.2.15 on 2026-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_snapshotpresenzaufficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_attivita',
            field=models.CharField(choices=[('SPO', 'Sportellista'), ('AMM', 'Amministrativista'), ('TEC', 'Tecnico')], db_index=True, default='AMM', max_length=3, verbose_name='Tipo di attività'),
        ),
    ]
