# Generated by Django 5.2.15 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_recapiti_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="badge",
            field=models.CharField(
                blank=True,
                help_text="Codice riportato nel file delle timbrature.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Badge presenze",
            ),
        ),
    ]
