# Generated by Django 5.2.15 on 2026-08-28

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="badge",
            field=models.CharField(
                blank=True,
                help_text="Codice riportato nel file delle timbrature.",
                max_length=10,
                null=True,
                unique=True,
                validators=[RegexValidator("^\\d{10}$", "Il badge deve essere composto da 10 cifre.")],
                verbose_name="Badge presenze",
            ),
        ),
    ]
