# Generated by Django 5.2.15 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customuser_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ultima_timbratura_causale",
            field=models.CharField(blank=True, editable=False, max_length=4, verbose_name="Causale ultima timbratura"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ultima_timbratura_il",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Ultima timbratura letta"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ultima_timbratura_verso",
            field=models.CharField(blank=True, editable=False, max_length=1, verbose_name="Verso ultima timbratura"),
        ),
    ]
