# Generated by Django 5.2.15 on 2026-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('su_appuntamento', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['giorno', 'ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Ufficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True, verbose_name='Codice')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('riceve_pubblico', models.BooleanField(default=True, verbose_name='Riceve il pubblico')),
                ('attivo', models.BooleanField(default=True)),
                ('piano', models.CharField(blank=True, max_length=20)),
                ('stanza', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ufficio',
                'verbose_name_plural': 'Uffici',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GruppoOrganizzativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('directory_name', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('ORG', 'Organizzativo'), ('TEC', 'Tecnico'), ('SEC', 'Sicurezza')], default='TEC', max_length=3)),
                ('sincronizzato', models.BooleanField(default=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('django_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_organizzativo', to='auth.group')),
            ],
            options={
                'verbose_name': 'Gruppo Organizzativo',
                'verbose_name_plural': 'Gruppi Organizzativi',
                'ordering': ['nome'],
            },
        ),
    ]
