# Generated by Django 5.2.15 on 2026-06-30 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ufficio',
            name='responsabile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uffici_responsabili', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gruppoorganizzativo',
            name='ufficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gruppi', to='access_control.ufficio'),
        ),
        migrations.AddField(
            model_name='calendarioapertura',
            name='ufficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperture', to='access_control.ufficio'),
        ),
        migrations.AddConstraint(
            model_name='calendarioapertura',
            constraint=models.UniqueConstraint(fields=('ufficio', 'giorno', 'ora_inizio', 'ora_fine'), name='uk_calendario_apertura'),
        ),
    ]
