# Generated by Django 5.2.15 on 2026-07-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppoorganizzativo',
            name='directory_sid',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='SID gruppo Active Directory'),
        ),
    ]
