# Generated by Django 5.2.15 on 2026-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_gruppoorganizzativo_directory_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ufficio',
            name='numero_visite_media',
            field=models.PositiveSmallIntegerField(default=50, help_text='Numero massimo di visite concluse utilizzate per calcolare il tempo medio di servizio.', verbose_name='Visite considerate per la media'),
        ),
        migrations.AddField(
            model_name='ufficio',
            name='overbooking',
            field=models.PositiveSmallIntegerField(default=0, help_text='Numero di visitatori che il sistema può accettare oltre la capacità stimata.', verbose_name='Tolleranza overbooking'),
        ),
        migrations.AddField(
            model_name='ufficio',
            name='tempo_medio_servizio_default',
            field=models.PositiveSmallIntegerField(default=20, help_text='Utilizzato quando non esistono ancora dati storici sufficienti per calcolare la durata media.', verbose_name='Tempo medio predefinito della visita (minuti)'),
        ),
    ]
