# Generated by Django 5.2.15 on 2026-09-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_alter_ufficio_prefisso_coda'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruppoorganizzativo',
            name='django_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_organizzativo', to='auth.group'),
        ),
    ]
