# Generated by Django 5.2.15 on 2026-09-02 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def trasferisci_collegamenti_e_assegnazioni(apps, schema_editor):
    GruppoOperativo = apps.get_model("access_control", "GruppoOrganizzativo")
    Ufficio = apps.get_model("access_control", "Ufficio")
    AssegnazioneUfficio = apps.get_model("access_control", "AssegnazioneUfficio")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    # Conserva il collegamento esistente, spostandolo dal gruppo all'ufficio.
    for gruppo in GruppoOperativo.objects.exclude(ufficio_id=None):
        Ufficio.objects.filter(pk=gruppo.ufficio_id).update(gruppo_operativo_id=gruppo.pk)

    # Le associazioni precedenti erano dedotte da "utente nel gruppo".
    # Le rendiamo esplicite, mantenendo invariata la situazione iniziale.
    for ufficio in Ufficio.objects.exclude(gruppo_operativo_id=None):
        for utente_id in User.objects.filter(groups=ufficio.gruppo_operativo.django_group_id).values_list("pk", flat=True):
            AssegnazioneUfficio.objects.get_or_create(
                utente_id=utente_id,
                ufficio_id=ufficio.pk,
                defaults={"attiva": True},
            )


def ripristina_collegamenti(apps, schema_editor):
    GruppoOperativo = apps.get_model("access_control", "GruppoOrganizzativo")
    Ufficio = apps.get_model("access_control", "Ufficio")
    for ufficio in Ufficio.objects.exclude(gruppo_operativo_id=None):
        # Al momento della prima applicazione la relazione era 1:1; in caso
        # di rollback successivo si mantiene il primo ufficio del gruppo.
        GruppoOperativo.objects.filter(
            pk=ufficio.gruppo_operativo_id,
            ufficio_id=None,
        ).update(ufficio_id=ufficio.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_alter_gruppoorganizzativo_django_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ufficio',
            name='gruppo_operativo',
            field=models.ForeignKey(blank=True, help_text='Gruppo Django/Active Directory ereditato dal personale assegnato a questo ufficio. Più uffici possono usare lo stesso gruppo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uffici', to='access_control.gruppoorganizzativo', verbose_name='Gruppo operativo'),
        ),
        migrations.CreateModel(
            name='AssegnazioneUfficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attiva', models.BooleanField(default=True)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni_personale', to='access_control.ufficio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni_ufficio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assegnazione ufficio',
                'verbose_name_plural': 'Assegnazioni uffici',
                'ordering': ['ufficio__nome', 'utente__last_name', 'utente__first_name'],
                'constraints': [models.UniqueConstraint(fields=('utente', 'ufficio'), name='uk_assegnazione_ufficio_utente')],
            },
        ),
        migrations.RunPython(trasferisci_collegamenti_e_assegnazioni, ripristina_collegamenti),
        migrations.RemoveField(
            model_name='gruppoorganizzativo',
            name='ufficio',
        ),
    ]
