# Generated by Django 5.2.15 on 2026-09-04 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_remove_gruppoorganizzativo_ufficio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndisponibilitaUfficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('attiva', models.BooleanField(default=True)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('comunicata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indisponibilita_uffici_comunicate', to=settings.AUTH_USER_MODEL)),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilita', to='access_control.ufficio')),
            ],
            options={
                'verbose_name': 'Indisponibilità ufficio',
                'verbose_name_plural': 'Indisponibilità uffici',
                'ordering': ['-data_inizio', 'ufficio__nome'],
            },
        ),
    ]
