"""
Django settings for ControlloAccessi project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "development-only-secret-key"
)

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in {
    "1", "true", "yes", "on"
}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        (
            "192.168.15.24,127.0.0.1,localhost,"
            "ticket.comune.aversa.ce.it,"
            "account.comune.aversa.ce.it,"
            "controlloaccessi.comune.aversa.ce.it,"
            "prenotazioni.comune.aversa.ce.it"
        ),
    ).split(",")
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts",
    "access_control",
    "visitors",
    "audit",
    "dashboard",
    "common",
    "post_office",
    "spid_cie",
    "prenotazioni",
    "pdnd",
    "comunicazioni",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'common.middleware.HostAccessMiddleware',
    'spid_cie.middleware.PublicBookingHostMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'common.module_access.AdminModuleAccessMiddleware',
    'accounts.middleware.ProfileCompletionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ControlloAccessi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ControlloAccessi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "controlloaccessi"),
        "USER": os.getenv("DB_USER", "controlloaccessi"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "it-it"

TIME_ZONE = "Europe/Rome"

USE_TZ = True

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.CustomUser"

AUTHENTICATION_BACKENDS = [
    "accounts.authentication.backend.ActiveDirectoryBackend",
    "django.contrib.auth.backends.ModelBackend",
]

###############################################################################
# DIRECTORY
###############################################################################

DIRECTORY_PROVIDER = "ACTIVE_DIRECTORY"

DIRECTORY = {
    # Configurazione LDAPS del primo Domain Controller. I valori possono
    # essere differenziati tra gli ambienti tramite /etc/controlloaccessi.env.
    "SERVER": os.getenv("AD_SERVER", "srvdomain.comuneaversa.local"),
    "PORT": int(os.getenv("AD_PORT", "636")),
    "USE_SSL": os.getenv("AD_USE_SSL", "True").lower() in {"1", "true", "yes", "on"},
    "TLS_CA_CERT_FILE": os.getenv(
        "AD_TLS_CA_CERT_FILE", str(BASE_DIR / "cert" / "srvdomain-ldaps.cer")
    ),
    "TLS_VALIDATE": os.getenv("AD_TLS_VALIDATE", "True").lower() in {"1", "true", "yes", "on"},
    "DOMAIN": os.getenv("AD_DOMAIN", "comuneaversa.local"),
    "BASE_DN": os.getenv(
        "AD_BASE_DN",
        "DC=comuneaversa,DC=local",
    ),
    "BIND_USER": os.getenv("AD_BIND_USER", ""),
    "BIND_PASSWORD": os.getenv("AD_BIND_PASSWORD", ""),
    "WRITE_ENABLED": os.getenv("AD_WRITE_ENABLED", "True").lower() in {"1", "true", "yes", "on"},
    "USER_SEARCH_BASE": os.getenv(
        "AD_USER_SEARCH_BASE",
        "CN=Users,DC=comuneaversa,DC=local",
    ),
    "GROUP_SEARCH_BASE": os.getenv(
        "AD_GROUP_SEARCH_BASE",
        "OU=Groups,DC=comuneaversa,DC=local",
    ),
    "AUTH_FORMAT": os.getenv("AD_AUTH_FORMAT", "UPN"),
    "DJANGO_STAFF_GROUPS": [
        item.strip()
        for item in os.getenv(
            "AD_DJANGO_STAFF_GROUPS",
            "Administrators,Django_Staff",
        ).split(",")
        if item.strip()
    ],
    "DJANGO_SUPERUSER_GROUPS": [
        item.strip()
        for item in os.getenv(
            "AD_DJANGO_SUPERUSER_GROUPS",
            "Django_Superuser,Administrators",
        ).split(",")
        if item.strip()
    ],
    "ADMINISTRATION_GROUP": os.getenv("AD_ADMINISTRATION_GROUP", "UffPersonale"),
    "GIUNTA_GROUP": "ASSESSORE",
    "CONSIGLIERI_GROUP": "CONSIGLIERE",
}


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

TICKET_PRINTER = {
    "ENABLED": os.getenv("TICKET_PRINTER_ENABLED", "False").lower()
    in {"1", "true", "yes", "on"},
    "HOST": os.getenv("TICKET_PRINTER_HOST", "192.168.15.80"),
    "PORT": int(os.getenv("TICKET_PRINTER_PORT", "9100")),
    "TIMEOUT": int(os.getenv("TICKET_PRINTER_TIMEOUT", "5")),
    "PRINT_QR": os.getenv("TICKET_PRINTER_PRINT_QR", "False").lower()
    in {"1", "true", "yes", "on"},
    "PUBLIC_TICKET_BASE_URL": os.getenv(
        "PUBLIC_TICKET_BASE_URL",
        "https://ticket.comune.aversa.ce.it",
    ),
}

# Separazione delle funzioni sui tre hostname. Il middleware applica questa
# regola anche dentro Django; il reverse proxy/firewall deve replicarla.
PUBLIC_TICKET_HOST = os.getenv(
    "PUBLIC_TICKET_HOST", "ticket.comune.aversa.ce.it"
).lower()
PUBLIC_ACCOUNT_HOST = os.getenv(
    "PUBLIC_ACCOUNT_HOST", "account.comune.aversa.ce.it"
).lower()
INTERNAL_APPLICATION_HOST = os.getenv(
    "INTERNAL_APPLICATION_HOST", "controlloaccessi.comune.aversa.ce.it"
).lower()
PUBLIC_TICKET_TOKEN_HOURS = int(
    os.getenv("PUBLIC_TICKET_TOKEN_HOURS", "24")
)
PUBLIC_BOOKING_HOST = os.getenv(
    "PUBLIC_BOOKING_HOST", "prenotazioni.comune.aversa.ce.it"
).lower()

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        (
            "https://ticket.comune.aversa.ce.it,"
            "https://account.comune.aversa.ce.it,"
            "https://controlloaccessi.comune.aversa.ce.it,"
            "https://prenotazioni.comune.aversa.ce.it"
        ),
    ).split(",")
    if origin.strip()
]

# Attivare a True quando gli hostname pubblici sono esposti in HTTPS.
SESSION_COOKIE_SECURE = os.getenv(
    "DJANGO_SESSION_COOKIE_SECURE", "False"
).lower() in {"1", "true", "yes", "on"}
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"


PRESENCE_CHECK_ENABLED = os.getenv(
    "PRESENCE_CHECK_ENABLED",
    "False",
).lower() in {"1", "true", "yes", "on"}

# Importazione presenze dal file timbrature esposto via SFTP/SSH.
PRESENCE_SSH_ENABLED = os.getenv("PRESENCE_SSH_ENABLED", "False").lower() in {"1", "true", "yes", "on"}
PRESENCE_SSH_HOST = os.getenv("PRESENCE_SSH_HOST", "")
PRESENCE_SSH_PORT = int(os.getenv("PRESENCE_SSH_PORT", "22"))
PRESENCE_SSH_USERNAME = os.getenv("PRESENCE_SSH_USERNAME", "")
PRESENCE_SSH_PRIVATE_KEY = os.getenv("PRESENCE_SSH_PRIVATE_KEY", "")
PRESENCE_SSH_KNOWN_HOSTS = os.getenv("PRESENCE_SSH_KNOWN_HOSTS", "")
PRESENCE_SSH_REMOTE_PATH = os.getenv("PRESENCE_SSH_REMOTE_PATH", "/C:/h/timbrature.txt")
PRESENCE_SSH_INTERVAL_SECONDS = int(os.getenv("PRESENCE_SSH_INTERVAL_SECONDS", "60"))

PORTINERIA_GROUP_NAME = os.getenv("PORTINERIA_GROUP_NAME", "Portineria")

# Coda e-mail gestita da django-post-office. Le credenziali SMTP restano
# esterne al repository e sono fornite con variabili d'ambiente.
EMAIL_BACKEND = "post_office.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 25))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {"1", "true", "yes", "on"}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "")
# Recapito dell'ufficio competente per le richieste di aggiornamento anagrafico.
ACCOUNT_UPDATE_CONTACT_EMAIL = os.getenv("ACCOUNT_UPDATE_CONTACT_EMAIL", EMAIL_HOST_USER)

# Domini disponibili per le nuove caselle di posta istituzionali.
INSTITUTIONAL_EMAIL_DOMAINS = (
    "comune.aversa.ce.it",
    "comuneaversa.local",
    "giunta.comune.aversa.ce.it",
)

POST_OFFICE = {
    "DEFAULT_PRIORITY": "medium",
    "MAX_RETRIES": 4,
}

# Accesso pubblico tramite la federazione/aggregatore OIDC dell'Ente.
# Credenziali e metadata restano nel file /etc/controlloaccessi.env.
SPID_CIE = {
    "ENABLED": os.getenv("SPID_CIE_ENABLED", "False").lower()
    in {"1", "true", "yes", "on"},
    "SERVER_METADATA_URL": os.getenv("SPID_CIE_SERVER_METADATA_URL", ""),
    "CLIENT_ID": os.getenv("SPID_CIE_CLIENT_ID", ""),
    "CLIENT_SECRET": os.getenv("SPID_CIE_CLIENT_SECRET", ""),
    "SCOPE": os.getenv("SPID_CIE_SCOPE", "openid profile email"),
}

# Gateway SAML separato: la chiave è condivisa solo fra gateway e applicazione.
SPID_GATEWAY = {
    "ENABLED": os.getenv("SPID_GATEWAY_ENABLED", "False").lower() in {"1", "true", "yes", "on"},
    "BASE_URL": os.getenv("SPID_GATEWAY_BASE_URL", "https://prenotazioni.comune.aversa.ce.it/identita/spid"),
    "SHARED_SECRET": os.getenv("SPID_GATEWAY_SHARED_SECRET", ""),
    "MAX_AGE_SECONDS": int(os.getenv("SPID_GATEWAY_MAX_AGE_SECONDS", "60")),
}

# App IO: inserire la chiave "use" del servizio nel file
# /etc/controlloaccessi.env. L'invio resta inattivo finché ENABLED è False.
APP_IO = {
    "ENABLED": os.getenv("APP_IO_ENABLED", "False").lower() in {"1", "true", "yes", "on"},
    "SUBSCRIPTION_KEY": os.getenv("APP_IO_SUBSCRIPTION_KEY", ""),
    "BASE_URL": os.getenv("APP_IO_BASE_URL", "https://api.io.pagopa.it/api/v1"),
    "TIMEOUT": int(os.getenv("APP_IO_TIMEOUT", "15")),
}

# PDND Interoperabilità. Ogni ENDPOINT e PURPOSE_ID viene rilasciato per lo
# specifico e-service dopo la richiesta di fruizione e la relativa finalità.
# La chiave privata non deve mai essere inclusa nel repository.
PDND = {
    "ENABLED": os.getenv("PDND_ENABLED", "False").lower() in {"1", "true", "yes", "on"},
    "TOKEN_URL": os.getenv("PDND_TOKEN_URL", "https://auth.interop.pagopa.it/token.oauth2"),
    "CLIENT_ASSERTION_AUDIENCE": os.getenv("PDND_CLIENT_ASSERTION_AUDIENCE", "https://auth.interop.pagopa.it/client-assertion"),
    "CLIENT_ID": os.getenv("PDND_CLIENT_ID", ""),
    "KID": os.getenv("PDND_KID", ""),
    "PRIVATE_KEY_PATH": os.getenv("PDND_PRIVATE_KEY_PATH", ""),
    "TIMEOUT": int(os.getenv("PDND_TIMEOUT", "20")),
    "SERVICES": {
        "ANPR_SOGGETTO": {"ENDPOINT": os.getenv("PDND_ANPR_SOGGETTO_ENDPOINT", ""), "PURPOSE_ID": os.getenv("PDND_ANPR_SOGGETTO_PURPOSE_ID", ""), "METHOD": os.getenv("PDND_ANPR_SOGGETTO_METHOD", "POST"), "PAYLOAD_FIELD": os.getenv("PDND_ANPR_SOGGETTO_PAYLOAD_FIELD", "codiceFiscale")},
        "ANPR_FAMIGLIA": {"ENDPOINT": os.getenv("PDND_ANPR_FAMIGLIA_ENDPOINT", ""), "PURPOSE_ID": os.getenv("PDND_ANPR_FAMIGLIA_PURPOSE_ID", ""), "METHOD": os.getenv("PDND_ANPR_FAMIGLIA_METHOD", "POST"), "PAYLOAD_FIELD": os.getenv("PDND_ANPR_FAMIGLIA_PAYLOAD_FIELD", "codiceFiscale")},
        "INPS_ISEE": {"ENDPOINT": os.getenv("PDND_INPS_ISEE_ENDPOINT", ""), "PURPOSE_ID": os.getenv("PDND_INPS_ISEE_PURPOSE_ID", ""), "METHOD": os.getenv("PDND_INPS_ISEE_METHOD", "POST"), "PAYLOAD_FIELD": os.getenv("PDND_INPS_ISEE_PAYLOAD_FIELD", "codiceFiscale")},
        "DURC": {"ENDPOINT": os.getenv("PDND_DURC_ENDPOINT", ""), "PURPOSE_ID": os.getenv("PDND_DURC_PURPOSE_ID", ""), "METHOD": os.getenv("PDND_DURC_METHOD", "POST"), "PAYLOAD_FIELD": os.getenv("PDND_DURC_PAYLOAD_FIELD", "codiceFiscale")},
    },
}

PRENOTAZIONI_DURATA_SLOT_MINUTI = int(
    os.getenv("PRENOTAZIONI_DURATA_SLOT_MINUTI", "30")
)
PRENOTAZIONI_MAX_GIORNI = int(
    os.getenv("PRENOTAZIONI_MAX_GIORNI", "90")
)

# Connettore verso il WordPress storico. La chiave HMAC e l'endpoint sono
# definiti solamente nell'ambiente di produzione.
WORDPRESS_APPOINTMENTS = {
    "ENABLED": os.getenv("WORDPRESS_APPOINTMENTS_ENABLED", "False").lower()
    in {"1", "true", "yes", "on"},
    "ENDPOINT": os.getenv("WORDPRESS_APPOINTMENTS_ENDPOINT", ""),
    "SHARED_SECRET": os.getenv("WORDPRESS_APPOINTMENTS_SHARED_SECRET", ""),
    "TIMEOUT": int(os.getenv("WORDPRESS_APPOINTMENTS_TIMEOUT", "30")),
    "PAGE_SIZE": int(os.getenv("WORDPRESS_APPOINTMENTS_PAGE_SIZE", "100")),
    "ANAGRAFICHE_ENDPOINT": os.getenv("WORDPRESS_ANAGRAFICHE_ENDPOINT", ""),
    "CALENDARI_ENDPOINT": os.getenv("WORDPRESS_CALENDARI_ENDPOINT", ""),
    "PERSONE_PUBBLICHE_ENDPOINT": os.getenv("WORDPRESS_PERSONE_PUBBLICHE_ENDPOINT", ""),
    "UNITE_ORGANIZZATIVE_ENDPOINT": os.getenv("WORDPRESS_UNITE_ORGANIZZATIVE_ENDPOINT", ""),
}

# Nginx / reverse proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ============================================================
# LOCAL DEVELOPMENT SETTINGS
# ============================================================

try:
    from .settings_develop import *
except ImportError:
    pass

# settings_develop può sostituire ALLOWED_HOSTS per i test locali: gli host
# previsti dall'applicazione devono comunque restare ammessi.
ALLOWED_HOSTS = list(
    dict.fromkeys(
        ALLOWED_HOSTS
        + [
            PUBLIC_TICKET_HOST,
            PUBLIC_ACCOUNT_HOST,
            INTERNAL_APPLICATION_HOST,
            PUBLIC_BOOKING_HOST,
        ]
    )
)
