"""
Django settings for ControlloAccessi project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "development-only-secret-key"
)

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in {
    "1", "true", "yes", "on"
}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        (
            "192.168.15.24,127.0.0.1,localhost,"
            "ticket.comune.aversa.ce.it,"
            "account.comune.aversa.ce.it,"
            "controlloaccessi.comune.aversa.ce.it"
        ),
    ).split(",")
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts",
    "access_control",
    "visitors",
    "audit",
    "dashboard",
    "common",
    "post_office",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'common.middleware.HostAccessMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.ProfileCompletionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ControlloAccessi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ControlloAccessi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "controlloaccessi"),
        "USER": os.getenv("DB_USER", "controlloaccessi"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "it-it"

TIME_ZONE = "Europe/Rome"

USE_TZ = True

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.CustomUser"

AUTHENTICATION_BACKENDS = [
    "accounts.authentication.backend.ActiveDirectoryBackend",
    "django.contrib.auth.backends.ModelBackend",
]

###############################################################################
# DIRECTORY
###############################################################################

DIRECTORY_PROVIDER = "ACTIVE_DIRECTORY"

DIRECTORY = {
    # Configurazione LDAPS del primo Domain Controller.
    "SERVER": "srvdomain.comuneaversa.local",
    "PORT": 636,
    "USE_SSL": True,
    "TLS_CA_CERT_FILE": BASE_DIR / "cert" / "srvdomain-ldaps.cer",
    "TLS_VALIDATE": True,
    "DOMAIN": os.getenv("AD_DOMAIN", "comuneaversa.local"),
    "BASE_DN": os.getenv(
        "AD_BASE_DN",
        "DC=comuneaversa,DC=local",
    ),
    "BIND_USER": os.getenv("AD_BIND_USER", ""),
    "BIND_PASSWORD": os.getenv("AD_BIND_PASSWORD", ""),
    "WRITE_ENABLED": os.getenv("AD_WRITE_ENABLED", "True").lower() in {"1", "true", "yes", "on"},
    "USER_SEARCH_BASE": os.getenv(
        "AD_USER_SEARCH_BASE",
        "CN=Users,DC=comuneaversa,DC=local",
    ),
    "GROUP_SEARCH_BASE": os.getenv(
        "AD_GROUP_SEARCH_BASE",
        "OU=Groups,DC=comuneaversa,DC=local",
    ),
    "AUTH_FORMAT": os.getenv("AD_AUTH_FORMAT", "UPN"),
    "DJANGO_STAFF_GROUPS": [
        item.strip()
        for item in os.getenv(
            "AD_DJANGO_STAFF_GROUPS",
            "Administrators,Django_Staff",
        ).split(",")
        if item.strip()
    ],
    "DJANGO_SUPERUSER_GROUPS": [
        item.strip()
        for item in os.getenv(
            "AD_DJANGO_SUPERUSER_GROUPS",
            "Django_Superuser,Administrators",
        ).split(",")
        if item.strip()
    ],
    "GIUNTA_GROUP": "ASSESSORE",
    "CONSIGLIERI_GROUP": "CONSIGLIERE",
}


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "login"

TICKET_PRINTER = {
    "ENABLED": os.getenv("TICKET_PRINTER_ENABLED", "False").lower()
    in {"1", "true", "yes", "on"},
    "HOST": os.getenv("TICKET_PRINTER_HOST", "192.168.15.80"),
    "PORT": int(os.getenv("TICKET_PRINTER_PORT", "9100")),
    "TIMEOUT": int(os.getenv("TICKET_PRINTER_TIMEOUT", "5")),
    "PRINT_QR": os.getenv("TICKET_PRINTER_PRINT_QR", "False").lower()
    in {"1", "true", "yes", "on"},
    "PUBLIC_TICKET_BASE_URL": os.getenv(
        "PUBLIC_TICKET_BASE_URL",
        "https://ticket.comune.aversa.ce.it",
    ),
}

# Separazione delle funzioni sui tre hostname. Il middleware applica questa
# regola anche dentro Django; il reverse proxy/firewall deve replicarla.
PUBLIC_TICKET_HOST = os.getenv(
    "PUBLIC_TICKET_HOST", "ticket.comune.aversa.ce.it"
).lower()
PUBLIC_ACCOUNT_HOST = os.getenv(
    "PUBLIC_ACCOUNT_HOST", "account.comune.aversa.ce.it"
).lower()
INTERNAL_APPLICATION_HOST = os.getenv(
    "INTERNAL_APPLICATION_HOST", "controlloaccessi.comune.aversa.ce.it"
).lower()
PUBLIC_TICKET_TOKEN_HOURS = int(
    os.getenv("PUBLIC_TICKET_TOKEN_HOURS", "24")
)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        (
            "https://ticket.comune.aversa.ce.it,"
            "https://account.comune.aversa.ce.it,"
            "https://controlloaccessi.comune.aversa.ce.it"
        ),
    ).split(",")
    if origin.strip()
]

# Attivare a True quando gli hostname pubblici sono esposti in HTTPS.
SESSION_COOKIE_SECURE = os.getenv(
    "DJANGO_SESSION_COOKIE_SECURE", "False"
).lower() in {"1", "true", "yes", "on"}
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"


PRESENCE_CHECK_ENABLED = os.getenv(
    "PRESENCE_CHECK_ENABLED",
    "False",
).lower() in {"1", "true", "yes", "on"}

PORTINERIA_GROUP_NAME = os.getenv("PORTINERIA_GROUP_NAME", "Portineria")

# Coda e-mail gestita da django-post-office. Le credenziali SMTP restano
# esterne al repository e sono fornite con variabili d'ambiente.
EMAIL_BACKEND = "post_office.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "mail.comune.aversa.ce.it")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "g.pannullo@comune.aversa.ce.it")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {"1", "true", "yes", "on"}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@comune.aversa.ce.it")
# Recapito dell'ufficio competente per le richieste di aggiornamento anagrafico.
ACCOUNT_UPDATE_CONTACT_EMAIL = os.getenv("ACCOUNT_UPDATE_CONTACT_EMAIL", EMAIL_HOST_USER)

# Domini disponibili per le nuove caselle di posta istituzionali.
INSTITUTIONAL_EMAIL_DOMAINS = (
    "comune.aversa.ce.it",
    "comuneaversa.local",
    "giunta.comune.aversa.ce.it",
)

POST_OFFICE = {
    "DEFAULT_PRIORITY": "medium",
    "MAX_RETRIES": 4,
}

# Nginx / reverse proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ============================================================
# LOCAL DEVELOPMENT SETTINGS
# ============================================================

try:
    from .settings_develop import *
except ImportError:
    pass

# settings_develop può sostituire ALLOWED_HOSTS per i test locali: gli host
# previsti dall'applicazione devono comunque restare ammessi.
ALLOWED_HOSTS = list(
    dict.fromkeys(
        ALLOWED_HOSTS
        + [
            PUBLIC_TICKET_HOST,
            PUBLIC_ACCOUNT_HOST,
            INTERNAL_APPLICATION_HOST,
        ]
    )
)
