# Generated by Django 5.2.15 on 2026-06-30 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('documento_tipo', models.CharField(blank=True, max_length=50)),
                ('documento_numero', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoVisitatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresso', models.DateTimeField(default=django.utils.timezone.now)),
                ('uscita', models.DateTimeField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('IN', 'In corso'), ('CH', 'Chiuso')], default='IN', max_length=2)),
                ('badge', models.CharField(blank=True, max_length=30)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('ufficio_destinazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visite', to='access_control.ufficio')),
                ('visitatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessi', to='visitors.visitatore')),
            ],
        ),
    ]
