# Generated by Django 5.2.15 on 2026-07-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cittadino', models.CharField(max_length=100)),
                ('cognome_cittadino', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('data_ora', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('stato', models.CharField(choices=[('PR', 'Prenotato'), ('CO', 'Confermato'), ('ES', 'Eseguito'), ('AN', 'Annullato'), ('NS', 'No show')], default='PR', max_length=2)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appuntamenti', to='access_control.ufficio')),
            ],
        ),
    ]
