# Generated by Django 5.2.15 on 2026-07-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_appuntamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitatore',
            name='documento_scadenza',
            field=models.DateField(blank=True, null=True, verbose_name='Scadenza documento'),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
