# Generated by Django 5.2.15 on 2026-07-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitatore_documento_scadenza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True, verbose_name='Codice badge')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badge',
                'ordering': ['codice'],
            },
        ),
        migrations.AlterField(
            model_name='accessovisitatore',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessi', to='visitors.badge', verbose_name='Badge'),
        ),
    ]
