# Generated by Django 5.2.15 on 2026-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_badge_alter_accessovisitatore_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessovisitatore',
            name='numero_coda',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Numero di coda'),
        ),
    ]
