# Generated by Django 5.2.15 on 2026-08-04 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_gruppoorganizzativo_directory_sid'),
        ('visitors', '0005_accessovisitatore_numero_coda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessovisitatore',
            options={'ordering': ['-ingresso'], 'verbose_name': 'Accesso visitatore', 'verbose_name_plural': 'Accessi visitatori'},
        ),
        migrations.AlterModelOptions(
            name='visitatore',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Visitatore', 'verbose_name_plural': 'Visitatori'},
        ),
        migrations.AddField(
            model_name='accessovisitatore',
            name='documento_presentato',
            field=models.BooleanField(default=True, verbose_name='Documento presentato'),
        ),
        migrations.AddField(
            model_name='visitatore',
            name='codice_fiscale',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='Codice fiscale'),
        ),
        migrations.AlterField(
            model_name='accessovisitatore',
            name='ingresso',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ingresso nella sede'),
        ),
        migrations.AlterField(
            model_name='accessovisitatore',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo della visita'),
        ),
        migrations.AlterField(
            model_name='accessovisitatore',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note della portineria'),
        ),
        migrations.AlterField(
            model_name='accessovisitatore',
            name='uscita',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uscita dalla sede'),
        ),
        migrations.AlterField(
            model_name='accessovisitatore',
            name='visitatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessi', to='visitors.visitatore'),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='cognome',
            field=models.CharField(max_length=100, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='documento_numero',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Numero documento'),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='documento_tipo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo documento'),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Telefono'),
        ),
        migrations.AddConstraint(
            model_name='accessovisitatore',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_coda__isnull', False)), fields=('ufficio_destinazione', 'numero_coda'), name='unique_queue_number_per_office'),
        ),
    ]
