# Generated by Django 5.2.15 on 2026-08-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_alter_accessovisitatore_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accessovisitatore',
            name='unique_queue_number_per_office',
        ),
    ]
