# Generated by Django 5.2.15 on 2026-08-05 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_gruppoorganizzativo_directory_sid'),
        ('visitors', '0007_remove_accessovisitatore_unique_queue_number_per_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessovisitatore',
            name='ingresso_ufficio_il',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ingresso nell'ufficio"),
        ),
        migrations.AddField(
            model_name='accessovisitatore',
            name='operatore_assegnato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessi_visitatori_gestiti', to=settings.AUTH_USER_MODEL, verbose_name='Dipendente assegnato'),
        ),
        migrations.AddField(
            model_name='accessovisitatore',
            name='spostato_fuori_ufficio_il',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Arrivo fuori dall'ufficio"),
        ),
        migrations.AddField(
            model_name='accessovisitatore',
            name='stato_coda',
            field=models.CharField(choices=[('HALL', 'In attesa nella hall'), ('PORTA', "In attesa fuori dall'ufficio"), ('UFF', "Dentro l'ufficio"), ('FINE', 'Visita conclusa'), ('ANN', 'Annullato')], db_index=True, default='HALL', max_length=5, verbose_name='Posizione nella coda'),
        ),
        migrations.AddField(
            model_name='accessovisitatore',
            name='visita_conclusa_il',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conclusione della visita'),
        ),
        migrations.CreateModel(
            name='SessioneRicevimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniziata_il', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inizio ricevimento')),
                ('terminata_il', models.DateTimeField(blank=True, null=True, verbose_name='Fine ricevimento')),
                ('attiva', models.BooleanField(db_index=True, default=True, verbose_name='Sessione attiva')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioni_ricevimento', to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioni_ricevimento', to='access_control.ufficio', verbose_name='Ufficio')),
            ],
            options={
                'verbose_name': 'Sessione di ricevimento',
                'verbose_name_plural': 'Sessioni di ricevimento',
                'ordering': ['-iniziata_il'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('attiva', True)), fields=('ufficio', 'operatore'), name='unique_active_reception_session')],
            },
        ),
    ]
