# Generated by Django 5.2.15 on 2026-08-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_accessovisitatore_ingresso_ufficio_il_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessovisitatore',
            name='appuntamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesso', to='visitors.appuntamento', verbose_name='Appuntamento collegato'),
        ),
    ]
