# Generated by Django 5.2.15 on 2026-08-07 09:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_ufficio_numero_visite_media_ufficio_overbooking_and_more'),
        ('visitors', '0009_accessovisitatore_appuntamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAccesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REG', 'Registrazione'), ('HAL', 'Ingresso in hall'), ('POR', 'Invio fuori ufficio'), ('CHI', 'Chiamata'), ('ING', 'Ingresso ufficio'), ('FIN', 'Visita conclusa'), ('USC', 'Uscita dalla sede'), ('NOT', 'Nota')], db_index=True, max_length=3, verbose_name='Tipo evento')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data e ora')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('dati', models.JSONField(blank=True, default=dict, verbose_name='Dati aggiuntivi')),
                ('accesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='visitors.accessovisitatore', verbose_name='Accesso')),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_accesso', to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
                ('ufficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_accesso', to='access_control.ufficio', verbose_name='Ufficio')),
            ],
            options={
                'verbose_name': 'Evento accesso',
                'verbose_name_plural': 'Eventi accesso',
                'ordering': ['-timestamp', '-pk'],
                'indexes': [models.Index(fields=['tipo', 'timestamp'], name='idx_evento_tipo_data'), models.Index(fields=['ufficio', 'tipo', 'timestamp'], name='idx_evento_uff_tipo')],
            },
        ),
    ]
