# Generated by Django 5.2.15 on 2026-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_eventoaccesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessovisitatore',
            name='tipo_accesso',
            field=models.CharField(choices=[('RICEVIMENTO', 'Ricevimento'), ('VISITA', 'Visita')], default='RICEVIMENTO', max_length=20),
        ),
    ]
