# Generated by Django 5.2.15 on 2026-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_accessovisitatore_tipo_accesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessovisitatore',
            name='tipo_accesso',
            field=models.CharField(choices=[('RIC', 'Ricevimento'), ('VIS', 'Visita')], db_index=True, default='RIC', max_length=3, verbose_name='Tipo accesso'),
        ),
    ]
