# Generated by Django 5.2.15 on 2026-08-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentitaDigitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SPID', 'SPID'), ('CIE', 'CIE')], max_length=4)),
                ('subject', models.CharField(max_length=255)),
                ('codice_fiscale', models.CharField(blank=True, db_index=True, max_length=16)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('autenticato_il', models.DateTimeField(auto_now=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Identità digitale',
                'verbose_name_plural': 'Identità digitali',
                'ordering': ['cognome', 'nome', 'provider'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='spid_cie_identita_provider_subject_unico')],
            },
        ),
    ]
