# Generated by Django 5.2.15 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("spid_cie", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="MessaggioIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codice_fiscale", models.CharField(db_index=True, max_length=16)),
                ("oggetto", models.CharField(max_length=120)),
                ("contenuto", models.TextField()),
                ("riferimento_esterno", models.CharField(blank=True, db_index=True, max_length=64)),
                ("messaggio_io_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("stato", models.CharField(choices=[("INVIATO", "Inviato a IO"), ("NON_CONFIGURATO", "Integrazione non configurata"), ("NON_ABILITATO", "Cittadino non abilitato al servizio"), ("ERRORE", "Errore di invio")], max_length=20)),
                ("risposta", models.TextField(blank=True)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "Messaggio App IO", "verbose_name_plural": "Messaggi App IO", "ordering": ["-creato_il"]},
        )
    ]
